name: get file content

on:
  workflow_dispatch:
  
jobs:
  get-content:
    runs-on: ubuntu-latest
    steps:
      - name: get content
        id: get-file
        shell: bash
        run: |
            curl -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.MY_PAT}}" \
                -H "X-GitHub-API-Version: 2022-11-28" \
                https://api.github.com/repos/madkoo/wic-app-mobile/contents/.github/docs/myjson.json \
                --output myfile.json

      - name: print file
        run: cat myfile.json
        
      - name: get content
        id: get-file-2
        shell: bash
        run: |
            curl -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.MY_PAT}}" \
                -H "X-GitHub-API-Version: 2022-11-28" \
                https://api.github.com/repos/madkoo/wic-app-mobile/contents/.github/docs/myjson.json \
                | jq -r ".content" | base64 --decode | output myfile2.json
                

      - name: print file
        run: cat myfile2.json
        
      - name: get content
        id: get-file-3
        shell: bash
        run: |
            curl -H "Accept: application/vnd.github.raw+json" \
                -H "Authorization: Bearer ${{secrets.MY_PAT}}" \
                -H "X-GitHub-API-Version: 2022-11-28" \
                https://api.github.com/repos/madkoo/wic-app-mobile/contents/.github/docs/myjson.json \
                --output myfile3.json

      - name: print file
        run: cat myfile3.json
             
     
