name: trigger on issue comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created,edited]
  
jobs:
  trigger-on-comment:
  runs-on: ubuntu-latest
  steps:
    - name:  add label
      uses: actions/github-scripts@v6
      script: | 
        await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['test-label']
            })    
  
