name: Trigger on issue

on:
  workflow_dispatch: 
  issues: 
    types: [opened, edited]
 
permissions:
    issues: write
    actions: read    
    
jobs:
  test-run:
    runs-on: ubuntu-latest
   
    steps:
    - name: First comment
      uses: actions/github-script@v6
      with:
        script: |
           const options = { token: '${{ secrets.MY_PAT }}' }
           await require('./.github/scripts/write-comment.js')({github, context, options})
          
  
