name: Trigger on issue

on:
  workflow_dispatch: 
  issues: 
    types: [opened, edited]
 
permissions:
    issues: write
    actions: read    
    
jobs:
  test-run:
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Check out repository for scripts
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2

      - name: Install Node dependencies
        run: npm install --no-save @octokit/rest
    
      - name: First comment
        uses: actions/github-script@v6
        with:
          script: |
             const options = { token: '${{ secrets.MY_PAT }}' }
             await require('./.github/scripts/write-comment.js')({github, context, options})

  
