name: Trigger on issue

on:
  workflow_dispatch: 
  issues: 
    types: [opened, edited]
 
    
    
jobs:
  test-run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: read
    steps:
    - name: First comment
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'write comment'
                  })
      env:
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          
  
