name: trigger on issue comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created,edited]
  
jobs:
  trigger-on-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name:  add label
        uses: actions/github-script@v6
        with:
          script: |
              await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    labels: ['test-label']
                  })    

